services:
  - type: web
    name: comunita-contest
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm ci --include=dev && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: next start -p $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_URL_UNPOOLED
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: VOTE_SALT
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: R2_BUCKET_PUBLIC
        sync: false
      - key: R2_PUBLIC_URL
        sync: false
